poli/evento/urls.py
from django.urls import path

from django.conf.urls import url
from evento import views
from .views import ConsolidadoEvento

urlpatterns = [
    path('evento/', views.HomeView.as_view(), name='homeEvento'),
    path('evento/<int:pk>/', views.EventoDetailView.as_view(), name='evento_detail'),
    path('evento/create/', views.EventoCreateView.as_view(), name='evento_create'),
    path('evento/update/<int:pk>/', views.EventoUpdateView.as_view(), name='evento_update'),
    path('evento/delete/<int:pk>/', views.EventoDeleteView.as_view(), name='evento_delete'),
    url(r'^ConsolidadoEvento/', ConsolidadoEvento.as_view(), name='ConsolidadoEvento'),
]

poli/persona/urls.py
from django.urls import path

from persona import views
from django.conf.urls import url
from .views import ConsolidadoPersona

urlpatterns = [
    path('persona/', views.HomeView.as_view(), name='homePersona'),
    path('persona/<int:pk>/', views.PersonaDetailView.as_view(), name='persona_detail'),
    path('persona/create/', views.PersonaCreateView.as_view(), name='persona_create'),
    path('persona/update/<int:pk>/', views.PersonaUpdateView.as_view(), name='persona_update'),
    path('persona/delete/<int:pk>/', views.PersonaDeleteView.as_view(), name='persona_delete'),
    url(r'^ConsolidadoPersona/', ConsolidadoPersona.as_view(), name='ConsolidadoPersona'),
]

poli/poli/urls.py
import io
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('ubicacion/', include(('ubicacion.urls', 'ubicacion'), namespace='ubicacion')),
    path('persona/', include(('persona.urls', 'persona'), namespace='persona')),
    path('registro/', include(('registro.urls', 'registro'), namespace='registro')),
    path('evento/', include(('evento.urls', 'evento'), namespace='evento')),
    #path('admin/', admin.site.urls),        
    url(r'^$', LoginView.as_view(template_name='base/login.html'), name='login'),
    url(r'^base/$', LoginView.as_view(template_name='base/welcome.html'), name='welcome'),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

poli/registro/urls.py
from django.urls import path

from registro import views

from django.conf.urls import url
from .views import ConsolidadoRegistro

urlpatterns = [
    path('registro/', views.HomeView.as_view(), name='homeRegistro'),
    path('registro/<int:pk>/', views.RegistroDetailView.as_view(), name='registro_detail'),
    path('registro/create/', views.RegistroCreateView.as_view(), name='registro_create'),
    path('registro/update/<int:pk>/', views.RegistroUpdateView.as_view(), name='registro_update'),
    path('registro/delete/<int:pk>/', views.RegistroDeleteView.as_view(), name='registro_delete'),
    url(r'^ConsolidadoRegistro/', ConsolidadoRegistro.as_view(), name='ConsolidadoRegistro'),
]

poli/ubicacion/urls.py
from django.urls import path

from django.conf.urls import url
from ubicacion import views
from .views import ConsolidadoUbicacion

urlpatterns = [
    path('ubicacion/', views.HomeView.as_view(), name='homeUbicacion'),
    path('ubicacion/<int:pk>/', views.UbicacionDetailView.as_view(), name='ubicacion_detail'),
    path('ubicacion/create/', views.UbicacionCreateView.as_view(), name='ubicacion_create'),
    path('ubicacion/update/<int:pk>/', views.UbicacionUpdateView.as_view(), name='ubicacion_update'),
    path('ubicacion/delete/<int:pk>/', views.UbicacionDeleteView.as_view(), name='ubicacion_delete'),
    url(r'^ConsolidadoUbicacion/', ConsolidadoUbicacion.as_view(), name='ConsolidadoUbicacion'),
]

poli/evento/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Evento(models.Model):
    id=models.AutoField(primary_key=True)
    codigo=models.CharField(max_length=5)
    nombre=models.CharField(max_length=50)
    tipoevento=[
        ('C', 'Cultural'),
        ('D', 'Diversión'),
        ('E', 'Educativo'),
        ('S', 'Social'),
        ('M', 'Musical'),
        ('D', 'Deportivo'),
        ('O', 'Otro')]
    tipo=models.CharField(max_length=1, choices=tipoevento, default='C')
    duracion=models.PositiveSmallIntegerField(default=120)
    descripcion=models.CharField(max_length=255)

    def __str__(self):
        txt="{0} (Duración: {1} minuto(s))"
        return txt.format(self.nombre, self.duracion)

    def get_absolute_url(self):
        return reverse('evento:evento_detail', kwargs={"pk": self.pk}) 

poli/persona/models.py
from django.db import models
from evento.models import Evento
from django.urls import reverse

# Create your models here.

class Persona(models.Model):
    numIdentificacion=models.CharField(max_length=20, primary_key=True)
    tipos=[
        ('C', 'Cédula de Ciudadanía'),
        ('E', 'Cédula de Extranjería'),
        ('P', 'Pasaporte'),
        ('O', 'Otro')]
    tipoIdentificacion=models.CharField(max_length=1, choices=tipos, default='C')
    apellidoPaterno=models.CharField(max_length=35)
    apellidoMaterno=models.CharField(max_length=35)
    nombres=models.CharField(max_length=50)
    fechaNacimiento=models.DateField()
    sexos=[
        ('F', 'Femenino'),
        ('M', 'Masculino'),
        ('X', 'Otro')]
    sexo=models.CharField(max_length=1, choices=sexos, default='M')
    telefono=models.CharField(max_length=15)
    direccion=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    evento=models.ForeignKey(Evento, null=False, blank=False, on_delete=models.CASCADE)

    def nombreCompleto(self):
        txt="{0} {1}, {2}"
        return txt.format(self.apellidoPaterno, self.apellidoMaterno, self.nombres)

    def __str__(self):
        txt="{0} / Evento: {1}"
        return txt.format(self.nombreCompleto(), self.evento)

    def get_absolute_url(self):
        return reverse('persona:persona_detail', kwargs={"pk": self.pk}) 

poli/registro/models.py
from django.db import models
from django.urls import reverse
from persona.models import Persona
from evento.models import Evento

# Create your models here.

class Registro(models.Model):
    id=models.AutoField(primary_key=True)
    persona=models.ForeignKey(Persona, null=False, blank=False, on_delete=models.CASCADE)
    evento=models.ForeignKey(Evento, null=False, blank=False, on_delete=models.CASCADE)
    fechaEvento=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        txt="{0} registrad{1} en el evento {2} / Fecha: {3}"
        if self.persona.sexo=="F":
            letraSexo="a"
        else:
            letraSexo="o"
        fecReg=self.fechaEvento.strftime("%A %d/%m/%Y %H:/%M:/%S")
        return txt.format(self.persona.nombreCompleto(), letraSexo, self.evento, fecReg)

    def get_absolute_url(self):
        return reverse('registro:registro_detail', kwargs={"pk": self.pk})

poli/evento/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.urls import reverse_lazy

from evento.models import Evento
from openpyxl import Workbook
from django.http.response import HttpResponse

# Create your views here.

class HomeView(ListView):
    model = Evento
    template_name = 'evento/index.html'
    paginate_by = 10


class EventoDetailView(DetailView):
    model = Evento
    template_name = 'evento/evento_detail.html'


class EventoCreateView(CreateView):
    model = Evento
    template_name = 'evento/evento_create.html'
    fields = ['codigo', 'nombre', 'tipo','duracion','descripcion']


class EventoUpdateView(UpdateView):
    model = Evento
    template_name = 'evento/evento_create.html'
    fields = ['codigo', 'nombre', 'tipo','duracion','descripcion']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class EventoDeleteView(DeleteView):
    model = Evento
    success_url = reverse_lazy('evento:homeEvento')
    template_name = 'evento/confirm_evento_deletion.html'

class ConsolidadoEvento(TemplateView):
    def get(self,request,*args,**kwargs):
        eventos = Evento.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'CONSOLIDADO DE EVENTOS'
        ws.merge_cells('B1:F1')
        ws['B3'] = 'CODIGO'
        ws['C3'] = 'NOMBRE'
        ws['D3'] = 'TIPO'
        ws['E3'] = 'DURACION'
        ws['F3'] = 'DESCRIPCION'
        cont = 4

        for evento in eventos:
            ws.cell(row = cont, column = 2).value = evento.codigo
            ws.cell(row = cont, column = 3).value = evento.nombre
            ws.cell(row = cont, column = 4).value = evento.tipo
            ws.cell(row = cont, column = 5).value = evento.duracion
            ws.cell(row = cont, column = 6).value = evento.descripcion
            cont+=1

        nombre_archivo = "ConsolidadoEvento.xlsx"
        response = HttpResponse(content_type = "applicacion/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response

poli/persona/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.views.generic import TemplateView
from persona.models import Persona

from openpyxl import Workbook
from django.http.response import HttpResponse

# Create your views here.

class HomeView(ListView):
    model = Persona
    template_name = 'persona/index.html'
    paginate_by = 10


class PersonaDetailView(DetailView):
    model = Persona
    template_name = 'persona/persona_detail.html'


class PersonaCreateView(CreateView):
    model = Persona
    template_name = 'persona/persona_create.html'
    fields = ['numIdentificacion', 'tipoIdentificacion', 'apellidoPaterno','apellidoMaterno','nombres','fechaNacimiento','sexo','telefono','direccion','email','evento']


class PersonaUpdateView(UpdateView):
    model = Persona
    template_name = 'persona/persona_create.html'
    fields = ['numIdentificacion', 'tipoIdentificacion', 'apellidoPaterno','apellidoMaterno','nombres','fechaNacimiento','sexo','telefono','direccion','email','evento']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class PersonaDeleteView(DeleteView):
    model = Persona
    success_url = reverse_lazy('persona:homePersona')
    template_name = 'persona/confirm_persona_deletion.html'

class ConsolidadoPersona(TemplateView):
    def get(self,request,*args,**kwargs):
        personas = Persona.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'CONSOLIDADO DE PERSONAS'
        ws.merge_cells('B1:L1')
        ws['B3'] = 'NO IDENTIFICACION'
        ws['C3'] = 'TIPO IDENTIFICACION'
        ws['D3'] = 'APELLIDO PATERNO'
        ws['E3'] = 'APELLIDO MATERNO'
        ws['F3'] = 'NOMBRES'
        ws['G3'] = 'FECHA NACIMIENTO'
        ws['H3'] = 'SEXO'
        ws['I3'] = 'TELEFONO'
        ws['J3'] = 'DIRECCION'
        ws['K3'] = 'EMAIL'
        #ws['L3'] = 'EVENTO'
        cont = 4

        for persona in personas:
            ws.cell(row = cont, column = 2).value = persona.numIdentificacion
            ws.cell(row = cont, column = 3).value = persona.tipoIdentificacion
            ws.cell(row = cont, column = 4).value = persona.apellidoPaterno
            ws.cell(row = cont, column = 5).value = persona.apellidoMaterno
            ws.cell(row = cont, column = 6).value = persona.nombres
            ws.cell(row = cont, column = 7).value = persona.fechaNacimiento
            ws.cell(row = cont, column = 8).value = persona.sexo
            ws.cell(row = cont, column = 9).value = persona.telefono
            ws.cell(row = cont, column = 10).value = persona.direccion
            ws.cell(row = cont, column = 11).value = persona.email
            #ws.cell(row = cont, column = 12).value = persona.evento
            cont+=1

        nombre_archivo = "ConsolidadoPersona.xlsx"
        response = HttpResponse(content_type = "applicacion/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response

poli/registro/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from registro.models import Registro

from openpyxl import Workbook
from django.http.response import HttpResponse

# Create your views here.

class HomeView(ListView):
    model = Registro
    template_name = 'registro/index.html'
    paginate_by = 10


class RegistroDetailView(DetailView):
    model = Registro
    template_name = 'registro/registro_detail.html'


class RegistroCreateView(CreateView):
    model = Registro
    template_name = 'registro/registro_create.html'
    fields = ['persona', 'evento']


class RegistroUpdateView(UpdateView):
    model = Registro
    template_name = 'registro/registro_create.html'
    fields = ['persona', 'evento']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class RegistroDeleteView(DeleteView):
    model = Registro
    success_url = reverse_lazy('registro:homeRegistro')
    template_name = 'registro/confirm_registro_deletion.html'

class ConsolidadoRegistro(TemplateView):
    def get(self,request,*args,**kwargs):
        registros = Registro.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'CONSOLIDADO DE REGISTROS'
        ws.merge_cells('B1:D1')
        #ws['B3'] = 'PERSONA'
        #ws['C3'] = 'EVENTO'
        ws['D3'] = 'FECHA DE EVENTO'
        cont = 4

        for registro in registros:
         #   ws.cell(row = cont, column = 2).value = registro.persona
         #   ws.cell(row = cont, column = 3).value = registro.evento
            ws.cell(row = cont, column = 4).value = registro.fechaEvento
            cont+=1

        nombre_archivo = "ConsolidadoRegistros.xlsx"
        response = HttpResponse(content_type = "applicacion/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response

poli/ubicacion/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import TemplateView

from ubicacion.models import Ubicacion

from openpyxl import Workbook
from django.http.response import HttpResponse

# Create your views here.

class HomeView(ListView):
    model = Ubicacion
    template_name = 'ubicacion/index.html'
    paginate_by = 10


class UbicacionDetailView(DetailView):
    model = Ubicacion
    template_name = 'ubicacion/ubicacion_detail.html'


class UbicacionCreateView(CreateView):
    model = Ubicacion
    template_name = 'ubicacion/ubicacion_create.html'
    fields = ['codigo', 'sector', 'nombre', 'capacidad']


class UbicacionUpdateView(UpdateView):
    model = Ubicacion
    template_name = 'ubicacion/ubicacion_create.html'
    fields = ['codigo', 'sector', 'nombre', 'capacidad']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['edit'] = True
        return context


class UbicacionDeleteView(DeleteView):
    model = Ubicacion
    success_url = reverse_lazy('ubicacion:homeUbicacion')
    template_name = 'ubicacion/confirm_ubicacion_deletion.html'

class ConsolidadoUbicacion(TemplateView):
    def get(self,request,*args,**kwargs):
        ubicaciones = Ubicacion.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'CONSOLIDADO DE UBICACIONES'
        ws.merge_cells('B1:E1')
        ws['B3'] = 'CODIGO'
        ws['C3'] = 'SECTOR'
        ws['D3'] = 'NOMBRE'
        ws['E3'] = 'CAPACIDAD'
        cont = 4

        for ubicacion in ubicaciones:
            ws.cell(row = cont, column = 2).value = ubicacion.codigo
            ws.cell(row = cont, column = 3).value = ubicacion.sector
            ws.cell(row = cont, column = 4).value = ubicacion.nombre
            ws.cell(row = cont, column = 5).value = ubicacion.capacidad
            cont+=1

        nombre_archivo = "ConsolidadoUbicacion.xlsx"
        response = HttpResponse(content_type = "applicacion/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response

poli/poli/templates/ubicacion/confirm_ubicacion_deletion.html
{% extends 'base/base.html' %}

{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}

            <p>Desea eliminar la Ubicación <b>"{{ ubicacion.nombre }}"</b> ?</p>

            <a href="{% url 'ubicacion:home' %}" class="btn btn-primary">No</a>
            <button class="btn btn-danger" type="submit">Si</button>
        </form>
    </div>
{% endblock %}

poli/poli/templates/ubicacion/index.html
{% extends 'base/base.html' %}

{% block content %}

<div class="container">
    {% if object_list %}
        <h2>Ubicaciones Configuradas</h2>
    {% endif %}
    
    <div class="row" style=" padding-top: 60px;">
        <div class="col-sm-12 col-md-12 col-lg-12 mx-auto" style="float: none; margin: 0 auto;">     
            <table class="table table-bordered">              
                <thead>
                <tr>
                    <th scope="col">Ubicación</th>
                    <th scope="col">Crear</th>
                    <th scope="col">Detalle</th>
                    <th scope="col">Modificar</th>
                    <th scope="col">Eliminar</th>
                </tr>
                </thead>
                <tbody>  
                    {% for ubicacion in object_list %}
                    <tr>
                        <td>{{ ubicacion.nombre }} </td>
                        <td><a href="{% url 'ubicacion:ubicacion_create' %}" ass="btn btn-success" role="button"><img src="https://img.icons8.com/pastel-glyph/2x/create-new.png" width="30px"></a></td>
                        <td><a href="{% url 'ubicacion:ubicacion_detail' ubicacion.pk %}" class="btn btn-info" role="button"><img  src="https://gecpdsomalia.org/wp-content/uploads/2016/11/circle-detail-more-icon-221.png" width="30px"></a></td>
                        <td><a href="{% url 'ubicacion:ubicacion_update' ubicacion.pk %}" class="btn btn-warning" role="button"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Edit_icon_%28the_Noun_Project_30184%29.svg/1024px-Edit_icon_%28the_Noun_Project_30184%29.svg.png" width="30px"></a></td>
                        <td><a href="{% url 'ubicacion:ubicacion_delete' ubicacion.pk %}" class="btn btn-danger" role="button"><img src="https://image.flaticon.com/icons/png/512/61/61848.png" width="30px"></a></td>  
                    </tr>
                    {% empty %}
                    <div class="empty-ubicacion">No existen ubicaciones en el sistema...</div>
                {% endfor %}
            
                </tbody>
            </table>
    <div>      
        <a href="{% url 'ubicacion:ConsolidadoUbicacion' %}"><button class="btn btn-primary" type="submit">Generar Consolidado - Excel</button></a>     
    </div>

    {% if page_obj.has_previous or page_obj.has_next %}
        <nav class="mt-4">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
</div>
{% endblock  %}

poli/poli/templates/ubicacion/ubicacion_create.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>
        {% if not edit %}
           Crear Ubicación
        {% else %}
            Editar Ubicación
        {% endif %}
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <div class="float-right">
            <a href="{% url 'ubicacion:home' %}" class="btn btn-danger">Regresar</a>
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </form>
{% endblock %}

poli/poli/templates/ubicacion/ubicacion_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h2">Nombre: {{ ubicacion.nombre }}</h2>
    <a href="{% url 'ubicacion:homeUbicacion' %}">Regresar</a>
    <a href="{% url 'ubicacion:ubicacion_update' ubicacion.pk %}">Modificar</a>
    <a href="{% url 'ubicacion:ubicacion_delete' ubicacion.pk %}">Eliminar</a>
    <hr />

    <p>Código: {{ ubicacion.codigo }}</p>
    <p>Sector: {{ ubicacion.zona }}</p>
    <p>Capacidad: {{ ubicacion.capacidad }}</p>   
    
    <div class="col-sm-10">   
        <a href="{% url 'ubicacion:homeUbicacion' %}" class="btn btn-danger">Regresar</a>
    </div> 
{% endblock  %}